<?php

use Illuminate\Database\Seeder;

class SkillSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * json
         */
        $skills = array(
        	['tag_name' => "Wordpress"],
        	['tag_name' => "Personal skills and knowledge"],
        	['tag_name' => "Driver's licence"],
        	['tag_name' => "First Aid"],
        	['tag_name' => "Community Development"],
        	['tag_name' => "Programming skills"],
        	['tag_name' => "C"],
        	['tag_name' => "C++"],
        	['tag_name' => "COBOL"],
        	['tag_name' => "Pascal"],
        	['tag_name' => "HTML"],
        	['tag_name' => "Java"],
        	['tag_name' => "Perl"],
        	['tag_name' => "ASP"],
        	['tag_name' => "Javascript"],
        	['tag_name' => "XML"],
        	['tag_name' => "SQL"],
        	['tag_name' => "C#"],
        	['tag_name' => "J#"],
        	['tag_name' => "Jscript"],
        	['tag_name' => "Visual Basic"],
        	['tag_name' => "PHP"],
        	['tag_name' => "Python"],
        	['tag_name' => "Ajax"],
        	['tag_name' => "CSS"],
        	['tag_name' => "FoxPro"],
        	['tag_name' => "Mercury"],
        	['tag_name' => "OPS5"],
        	['tag_name' => "Prolog"],
        	['tag_name' => "Ruby"],
        	['tag_name' => "GIT"],
        	['tag_name' => "CVS"],
        	['tag_name' => "HTML 5"],
        	['tag_name' => "Objective C"],
        	['tag_name' => "Assembly"],
        	['tag_name' => "Unix shell scripting"],
        	['tag_name' => "Network management and data transmission"],
        	['tag_name' => "Novell netware"],['tag_name' => "IPX"],
        	['tag_name' => "TCP/IP"],
        	['tag_name' => "LAN (local area network)"],
        	['tag_name' => "WAN (wide area network)"],
        	['tag_name' => "WAP (Wireless Application Protocol)"],
        	['tag_name' => "Voice - IP Telephony (VoIP)"],
        	['tag_name' => "UMTS/GSM network management"],
        	['tag_name' => "Network Design"],
        	['tag_name' => "Network security"],
        	['tag_name' => "Optical fibers"],
        	['tag_name' => "WDM"],
        	['tag_name' => "IP/MPLS"],
        	['tag_name' => "Microwave Transmission"],
        	['tag_name' => "Operating systems"],
        	['tag_name' => "UNIX/Linux OS"],
        	['tag_name' => "X-Windows"],
        	['tag_name' => "Windows Operating Systems"],
        	['tag_name' => "MacOS"],
        	['tag_name' => "AS/400"],
        	['tag_name' => "Android"],
        	['tag_name' => "iOS"],
        	['tag_name' => "ERP"],
        	['tag_name' => "Baan"],
        	['tag_name' => "PeopleSoft"],
        	['tag_name' => "SAP"],
        	['tag_name' => "Microsoft Business Solution"],
        	['tag_name' => "Salesforce"],
        	['tag_name' => "Siebel"],
        	['tag_name' => "Oracle"],
        	['tag_name' => "Groupware"],
        	['tag_name' => "Lotus Notes/Domino"],
        	['tag_name' => "MS Exchange"],
        	['tag_name' => "Novell Groupwise"],
        	['tag_name' => "Development Environment (IDE)"],
        	['tag_name' => "Visual Basic"],
        	['tag_name' => "Database Design and Development Tools"],
        	['tag_name' => "Delphi"],
        	['tag_name' => "Other Development Tools"],
        	['tag_name' => "Powerbuilder"],
        	['tag_name' => "Visual Studio"],
        	['tag_name' => "Visual C++"],
        	['tag_name' => "Eclipse"],
        	['tag_name' => "Netbeans"],
        	['tag_name' => "Databases"],
        	['tag_name' => "Microsoft Access"],
        	['tag_name' => "DB/2"],
        	['tag_name' => "Microsoft SQL Server"],
        	['tag_name' => "Oracle"],
        	['tag_name' => "Sybase"],
        	['tag_name' => "PostgreSQL"],
        	['tag_name' => "MySQL"],
        	['tag_name' => "NoSQL"],
        	['tag_name' => "MongoDB"],
        	['tag_name' => "Graphics and Design"],
        	['tag_name' => "3D Max"],
        	['tag_name' => "Auto-CAD"],
        	['tag_name' => "Corel Draw"],
        	['tag_name' => "Adobe"],
        	['tag_name' => "Photoshop"],
        	['tag_name' => "Shockwave Flash"],
        	['tag_name' => "Professional Skills"],
        	['tag_name' => "Organisational Management"],
        	['tag_name' => "Team Management"],
        	['tag_name' => "Project Management"],
        	['tag_name' => "Training/ Facilitating skills"],
        	['tag_name' => "Leadership skills"],
        	['tag_name' => "Presentation skills"],
        	['tag_name' => "Financial Management skills"],
        	['tag_name' => "Marketing / Selling skills"],
        	['tag_name' => "Language Teaching"],
        	['tag_name' => "Client Servicing Skills"],
        	['tag_name' => "Computer"],
        	['tag_name' => "PC User Skills"],
        	['tag_name' => "Mac User Skills"],
        	['tag_name' => "Internet User Skills"],
        	['tag_name' => "Mechanical Engineering"],
        	['tag_name' => "Computer aided design"],
        	['tag_name' => "Material Science"],
        	['tag_name' => "Aerospace Engineering"],
        	['tag_name' => "Fluid Mechanics"],
        	['tag_name' => "Automotive Engineering"],
        	['tag_name' => "Engineering Mechanics"],
        	['tag_name' => "Aircraft Engine Technology"],
        	['tag_name' => "Rotor Technology"],
        	['tag_name' => "Process Engineering"],
        	['tag_name' => "Designing Commercial Aircrafts"],
        	['tag_name' => "Machine Elements"],
        	['tag_name' => "Fuel Cells"],
        	['tag_name' => "Thermodynamics"],
        	['tag_name' => "Mass and Heat Transfer"],
        	['tag_name' => "Construction Engineering"],
        	['tag_name' => "Operations Research"],
        	['tag_name' => "Ergonomics"],
        	['tag_name' => "Manufacturing Technology"],
        	['tag_name' => "Civil Engineering / Environmental Engineering"],
        	['tag_name' => "Mechanics"],
        	['tag_name' => "Static"],
        	['tag_name' => "Wood Construction"],
        	['tag_name' => "Solid Construction"],
        	['tag_name' => "Steel Construction"],
        	['tag_name' => "Technology of Building Materials"],
        	['tag_name' => "Fire Safety Engineering"],
        	['tag_name' => "Introductory Structural design"],
        	['tag_name' => "Construction Management"],
        	['tag_name' => "Soil Mechanics"],
        	['tag_name' => "Hydrology"],
        	['tag_name' => "Hydromechanics"],
        	['tag_name' => "Renewable Energies"],
        	['tag_name' => "Process Engineering"],
        	['tag_name' => "Waste \u0026 Water Management"],
        	['tag_name' => "Ecology"],
        	['tag_name' => "Software Development Frameworks"],
        	['tag_name' => "Zend"],
        	['tag_name' => "Yii"],
        	['tag_name' => "Cake PHP"],
        	['tag_name' => "CodeIgniter"],
        	['tag_name' => "Symfony"],
        	['tag_name' => "Ruby on Rails"],
        	['tag_name' => "Java EE"],
        	['tag_name' => "Struts"],
        	['tag_name' => ".NET"],
        	['tag_name' => "GTK"],
        	['tag_name' => "Qt"],
        	['tag_name' => "jQuery"],
        	['tag_name' => "Protype"],
        	['tag_name' => "Node.js"],
        	['tag_name' => "Django"],
        	['tag_name' => "Content Management Systems"],
        	['tag_name' => "Joomla"],
        	['tag_name' => "Drupal"]
        );

		//loop through the array and create a new record in the database for every element.
		foreach ($skills as $key => $skill) {
			App\models\Skill::create($skill);
		}
    }    
}
